const actionLabels: Record<string, string> = {
  PROTOCOL_CREATED: 'Processo criado',
  PROTOCOL_UPDATED: 'Dados do processo atualizados',
  PROTOCOL_DELETED: 'Processo excluído',
  PROTOCOL_ASSUMED: 'Responsabilidade assumida',
  PROTOCOL_ACKNOWLEDGED: 'Ciência registrada',
  PROTOCOL_CHECKLIST_UPDATED: 'Checklist atualizado',
  PROTOCOL_ASSIGNEE_CHANGED: 'Responsável alterado',
  PROTOCOL_FORWARDED: 'Processo tramitado',
  PROTOCOL_COMPLETED: 'Processo concluído',
  PROTOCOL_PHASE_ADVANCED: 'Fase avançada',
  PROTOCOL_PHASE_RETURNED: 'Fase devolvida',
  PROTOCOL_ARCHIVED: 'Processo arquivado',
  PROTOCOL_REOPENED: 'Processo reaberto',
  PROTOCOL_DOSSIER_GENERATED: 'Dossiê gerado',
  ATTACHMENT_ADDED: 'Arquivo anexado',
  ATTACHMENT_DELETED: 'Anexo excluído',
  ATTACHMENT_UPDATED: 'Anexo atualizado',
  DOCUMENT_CREATED: 'Documento criado',
  DOCUMENT_LINKED: 'Documento vinculado ao processo',
  DOCUMENT_UPDATED: 'Documento atualizado',
  DOCUMENT_DELETED: 'Documento excluído',
  DOCUMENT_TEMPLATE_CREATED: 'Modelo de documento criado',
  DOCUMENT_TEMPLATE_UPDATED: 'Modelo de documento atualizado',
  DOCUMENT_TEMPLATE_DELETED: 'Modelo de documento excluído',
  USER_CREATED: 'Usuário criado',
  USER_UPDATED: 'Usuário atualizado',
  USER_MEMBERSHIP_CREATED: 'Acesso à unidade concedido',
  USER_MEMBERSHIP_UPDATED: 'Acesso à unidade atualizado',
  USER_MEMBERSHIP_REMOVED: 'Acesso à unidade removido',
  PERSON_CREATED: 'Pessoa cadastrada',
  PERSON_UPDATED: 'Pessoa atualizada',
  UNIT_REPARENTED: 'Hierarquia da unidade alterada',
  UNIT_DELETED: 'Unidade excluída',
  SITUATION_CREATED: 'Situação criada',
  SITUATION_UPDATED: 'Situação atualizada',
  SITUATION_DELETED: 'Situação excluída',
  PHASE_CREATED: 'Fase criada',
  PHASE_UPDATED: 'Fase atualizada',
  PHASE_DELETED: 'Fase excluída',
  CATEGORY_CREATED: 'Categoria criada',
  CATEGORY_UPDATED: 'Categoria atualizada',
  CATEGORY_DELETED: 'Categoria excluída',
  PROFILE_CREATED: 'Perfil de acesso criado',
  PROFILE_UPDATED: 'Perfil de acesso atualizado',
  PROFILE_DELETED: 'Perfil de acesso excluído',
}

export function auditActionLabel(action: string): string {
  return Object.prototype.hasOwnProperty.call(actionLabels, action) ? actionLabels[action] : 'Ação registrada'
}
