import type { AppDocument, AppUser, Attachment, Context, Database, Person, Protocol, Unit, ProtocolType, DocumentType, ProtocolEvent, ProtocolStatus } from '../domain/model'
import { isActive } from '../domain/model'
import { canAct, canView, DomainError, getAssignment, getProtocol, getUser, requireActive, requireActor, requireAdmin, requireAssignmentReceived, requireVersion } from '../domain/rules'
import { cleanupOrphanedBlobs, deleteBlob, getBlob, loadDb, putBlob, saveDb } from '../storage/database'
import { isoDaysFromNow } from '../lib/format'

const sleep = () => new Promise((resolve) => window.setTimeout(resolve, 110))
const id = () => crypto.randomUUID()
const event = (db: Database, data: Omit<ProtocolEvent, 'id' | 'createdAt'>) => db.events.push({ ...data, id: id(), createdAt: new Date().toISOString() })
const mutate = async <T>(fn: (db: Database) => T) => { await sleep(); const db = loadDb(); const value = fn(db); saveDb(db); window.dispatchEvent(new Event('fluxo-publico:changed')); window.dispatchEvent(new CustomEvent('fluxo-publico:toast', { detail: { kind: 'success', message: 'Alteração salva com sucesso.' } })); return value }
const protocolType = (db: Database, typeId: string) => db.protocolTypes.find((t) => t.id === typeId) ?? (() => { throw new DomainError('NOT_FOUND', 'Tipo de protocolo não encontrado.') })()
const nextNumber = (db: Database, scope: 'protocol' | 'document') => { const year = new Date().getFullYear(); const key = `${scope}-${year}`; db.counters[key] = (db.counters[key] ?? 0) + 1; return `${scope === 'protocol' ? year : `DOC-${year}`}.${String(db.counters[key]).padStart(6, '0')}` }
const bump = (p: Protocol) => { p.version += 1; p.updatedAt = new Date().toISOString() }
const endCurrent = (db: Database, p: Protocol) => { getAssignment(db, p).endedAt = new Date().toISOString() }
const addAssignment = (db: Database, p: Protocol, unitId: string, assigneeId?: string) => { const assignment = { id: id(), protocolId: p.id, unitId, assigneeId, startedAt: new Date().toISOString() }; db.assignments.push(assignment); p.currentAssignmentId = assignment.id; p.currentUnitId = unitId; p.currentAssigneeId = assigneeId; return assignment }
type PersonInput = Omit<Person, 'id'>
const documentIsValid = (value: string) => {
  const digits = value.replace(/\D/g, '')
  if (digits.length !== 11 && digits.length !== 14) return false
  if (/^(\d)\1+$/.test(digits)) return false
  const weights = digits.length === 11 ? [10, 9, 8, 7, 6, 5, 4, 3, 2] : [5, 4, 3, 2, 9, 8, 7, 6, 5, 4, 3, 2]
  const check = (source: string, factors: number[]) => { const sum = source.split('').reduce((total, digit, index) => total + Number(digit) * factors[index], 0); const result = sum % 11; return result < 2 ? 0 : 11 - result }
  const first = check(digits.slice(0, -2), weights)
  const secondWeights = digits.length === 11 ? [11, 10, 9, 8, 7, 6, 5, 4, 3, 2] : [6, 5, 4, 3, 2, 9, 8, 7, 6, 5, 4, 3, 2]
  return Number(digits.at(-2)) === first && Number(digits.at(-1)) === check(`${digits.slice(0, -2)}${first}`, secondWeights)
}
const attachmentPreviewKind = (mimeType: string): 'pdf' | 'image' | 'text' | undefined => { if (mimeType === 'application/pdf') return 'pdf'; if (mimeType === 'image/png' || mimeType === 'image/jpeg') return 'image'; if (mimeType === 'text/plain') return 'text'; return undefined }
const validatePerson = (input: PersonInput) => {
  if (!input.name.trim() || !input.roles.length) throw new DomainError('VALIDATION', 'Informe nome e ao menos um papel.')
  if (input.document && !documentIsValid(input.document)) throw new DomainError('VALIDATION', 'CPF ou CNPJ inválido.')
  if (input.email && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(input.email)) throw new DomainError('VALIDATION', 'E-mail inválido.')
  if (input.phone && input.phone.replace(/\D/g, '').length < 10) throw new DomainError('VALIDATION', 'Telefone inválido.')
}

type ProtocolTypeInput = Omit<ProtocolType, 'id'>
const validateProtocolType = (input: ProtocolTypeInput) => {
  if (!input.name.trim() || !input.description.trim()) throw new DomainError('VALIDATION', 'Informe nome e descrição do tipo.')
  if (input.defaultDeadlineDays !== undefined && (!Number.isInteger(input.defaultDeadlineDays) || input.defaultDeadlineDays < 1)) throw new DomainError('VALIDATION', 'Prazo padrão deve ser um número inteiro positivo.')
  for (const config of Object.values(input.fieldsConfig)) if (config.required && !config.enabled) throw new DomainError('VALIDATION', 'Não é possível exigir um campo desabilitado.')
}

type UserInput = Omit<AppUser, 'id'>
const validateUser = (db: Database, input: UserInput, ignoreId?: string) => {
  if (!input.name.trim() || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(input.email)) throw new DomainError('VALIDATION', 'Informe nome e e-mail válidos.')
  if (!db.units.some((unit) => unit.id === input.unitId && unit.active)) throw new DomainError('VALIDATION', 'Selecione uma unidade ativa.')
  if (db.users.some((user) => user.id !== ignoreId && user.email.toLocaleLowerCase() === input.email.trim().toLocaleLowerCase())) throw new DomainError('VALIDATION', 'Já existe um usuário com este e-mail.')
}
export interface ProtocolFilters { tab?: 'mine' | 'unit' | 'created' | 'all'; search?: string; status?: ProtocolStatus | ''; typeId?: string; unitId?: string; assigneeId?: string; createdFrom?: string; createdTo?: string; sort?: 'updated-desc' | 'created-desc' | 'due-asc' | 'number-asc'; shortcut?: 'unassigned' | 'unacknowledged' | 'overdue' | 'soon' | ''; page?: number; pageSize?: number }
export const api = {
  attachmentPreviewKind,
  async dashboard(ctx: Context) { await sleep(); const db = loadDb(); requireActor(db, ctx); const now = new Date(); const visible = db.protocols.filter((p) => canView(db, p, ctx)); const mine = visible.filter((p) => isActive(p) && p.currentAssigneeId === ctx.userId); const unit = visible.filter((p) => isActive(p) && p.currentUnitId === ctx.activeUnitId); const currentAssignment = (p: Protocol) => getAssignment(db, p); return { counts: { mine: mine.length, unassigned: unit.filter((p) => !p.currentAssigneeId).length, overdue: unit.filter((p) => !!p.dueAt && new Date(p.dueAt) < now).length, soon: unit.filter((p) => !!p.dueAt && new Date(p.dueAt) >= now && new Date(p.dueAt).getTime() <= now.getTime() + 86400000).length }, priorities: [...mine, ...unit.filter((p) => !p.currentAssigneeId)].filter((p, i, a) => a.findIndex((x) => x.id === p.id) === i).sort((a, b) => Number(!!b.dueAt && new Date(b.dueAt) < now) - Number(!!a.dueAt && new Date(a.dueAt) < now) || (a.dueAt ?? 'z').localeCompare(b.dueAt ?? 'z')).slice(0, 8), events: db.events.filter((e) => visible.some((p) => p.id === e.protocolId)).sort((a, b) => b.createdAt.localeCompare(a.createdAt)).slice(0, 7), received: currentAssignment }
  },
  async listProtocols(ctx: Context, filters: ProtocolFilters = {}) { await sleep(); const db = loadDb(); const user = requireActor(db, ctx); let items = db.protocols.filter((p) => canView(db, p, ctx)); const tab = filters.tab ?? 'mine'; if (tab === 'mine') items = items.filter((p) => isActive(p) && p.currentAssigneeId === user.id); if (tab === 'unit') items = items.filter((p) => isActive(p) && p.currentUnitId === ctx.activeUnitId); if (tab === 'created') items = items.filter((p) => p.createdById === user.id); if (filters.search) { const q = filters.search.toLocaleLowerCase(); items = items.filter((p) => p.number.includes(q) || p.subject.toLocaleLowerCase().includes(q) || db.people.find((x) => x.id === p.interestedPersonId)?.name.toLocaleLowerCase().includes(q)) }
    if (filters.status) items = items.filter((p) => p.status === filters.status); if (filters.typeId) items = items.filter((p) => p.typeId === filters.typeId); if (filters.unitId) items = items.filter((p) => p.currentUnitId === filters.unitId); if (filters.assigneeId) items = items.filter((p) => p.currentAssigneeId === filters.assigneeId); if (filters.createdFrom) items = items.filter((p) => p.createdAt >= filters.createdFrom!); if (filters.createdTo) { const end = new Date(filters.createdTo); end.setHours(23, 59, 59, 999); items = items.filter((p) => new Date(p.createdAt) <= end) }; const now = new Date(); if (filters.shortcut === 'unassigned') items = items.filter((p) => !p.currentAssigneeId); if (filters.shortcut === 'unacknowledged') items = items.filter((p) => !getAssignment(db, p).receivedAt); if (filters.shortcut === 'overdue') items = items.filter((p) => isActive(p) && !!p.dueAt && new Date(p.dueAt) < now); if (filters.shortcut === 'soon') items = items.filter((p) => isActive(p) && !!p.dueAt && new Date(p.dueAt) >= now && new Date(p.dueAt).getTime() < now.getTime() + 86400000); items.sort((a, b) => { if (filters.sort === 'created-desc') return b.createdAt.localeCompare(a.createdAt); if (filters.sort === 'number-asc') return a.number.localeCompare(b.number); if (filters.sort === 'due-asc') return (a.dueAt ?? '9999').localeCompare(b.dueAt ?? '9999'); return b.updatedAt.localeCompare(a.updatedAt) }); const pageSize = filters.pageSize ?? 10; const total = items.length; const page = Math.min(filters.page ?? 1, Math.max(1, Math.ceil(total / pageSize))); return { items: items.slice((page - 1) * pageSize, page * pageSize), total, page, pageSize }
  },
  async getProtocol(ctx: Context, protocolId: string) { await sleep(); const db = loadDb(); requireActor(db, ctx); const protocol = getProtocol(db, protocolId); if (!canView(db, protocol, ctx)) throw new DomainError('FORBIDDEN', 'Você não possui acesso a este protocolo.'); return { protocol, assignment: getAssignment(db, protocol), events: db.events.filter((e) => e.protocolId === protocolId).sort((a, b) => b.createdAt.localeCompare(a.createdAt)), attachments: db.attachments.filter((a) => a.protocolId === protocolId), documents: db.documents.filter((d) => d.protocolId === protocolId), db } },
  async createProtocol(ctx: Context, input: { typeId: string; subject: string; description: string; interestedPersonId?: string; creditorPersonId?: string; amountCents?: number; dueAt?: string }) { return mutate((db) => { const user = requireActor(db, ctx); if (user.unitId !== ctx.activeUnitId) throw new DomainError('FORBIDDEN', 'Para abrir, selecione a sua unidade de vínculo.'); const type = protocolType(db, input.typeId); if (!input.subject.trim() || input.subject.length > 160) throw new DomainError('VALIDATION', 'Informe um assunto de até 160 caracteres.'); if (!input.description.trim() || input.description.length > 4000) throw new DomainError('VALIDATION', 'Informe uma descrição de até 4.000 caracteres.'); for (const [key, value] of Object.entries({ interested: input.interestedPersonId, creditor: input.creditorPersonId, amount: input.amountCents })) { const setting = type.fieldsConfig[key as keyof typeof type.fieldsConfig]; if (setting.required && (value === undefined || value === '')) throw new DomainError('VALIDATION', `Preencha o campo obrigatório: ${key}.`) } if (input.amountCents !== undefined && input.amountCents < 0) throw new DomainError('VALIDATION', 'Valor não pode ser negativo.'); const createdAt = new Date().toISOString(); const assignment = { id: id(), protocolId: id(), unitId: ctx.activeUnitId, assigneeId: user.id, startedAt: createdAt, receivedAt: createdAt, receivedById: user.id }; const p: Protocol = { id: assignment.protocolId, number: nextNumber(db, 'protocol'), typeId: type.id, typeConfigSnapshot: structuredClone(type.fieldsConfig), subject: input.subject.trim(), description: input.description.trim(), interestedPersonId: input.interestedPersonId, creditorPersonId: input.creditorPersonId, amountCents: input.amountCents, status: 'CADASTRADO', originUnitId: ctx.activeUnitId, currentUnitId: ctx.activeUnitId, currentAssigneeId: user.id, currentAssignmentId: assignment.id, dueAt: input.dueAt, createdById: user.id, createdAt, updatedAt: createdAt, version: 1 }; db.protocols.push(p); db.assignments.push(assignment); event(db, { protocolId: p.id, kind: 'ABERTURA', actorUserId: user.id, actorUnitId: ctx.activeUnitId, toUnitId: ctx.activeUnitId, toUserId: user.id, assignmentId: assignment.id, nextStatus: 'CADASTRADO' }); event(db, { protocolId: p.id, kind: 'RECEBIMENTO', actorUserId: user.id, actorUnitId: ctx.activeUnitId, assignmentId: assignment.id }); return p }) },
  async assume(ctx: Context, protocolId: string, expectedVersion: number) { return mutate((db) => { const p = getProtocol(db, protocolId); requireVersion(p, expectedVersion); requireActive(p); const user = requireActor(db, ctx); if (p.currentUnitId !== user.unitId || ctx.activeUnitId !== user.unitId || p.currentAssigneeId) throw new DomainError('FORBIDDEN', 'Apenas a fila da sua unidade pode ser assumida.'); const a = getAssignment(db, p); a.assigneeId = user.id; a.receivedAt = new Date().toISOString(); a.receivedById = user.id; p.currentAssigneeId = user.id; bump(p); event(db, { protocolId, kind: 'ATRIBUICAO', actorUserId: user.id, actorUnitId: ctx.activeUnitId, toUserId: user.id, assignmentId: a.id }); event(db, { protocolId, kind: 'RECEBIMENTO', actorUserId: user.id, actorUnitId: ctx.activeUnitId, assignmentId: a.id }); return p }) },
  async acknowledge(ctx: Context, protocolId: string, expectedVersion: number) { return mutate((db) => { const p = getProtocol(db, protocolId); requireVersion(p, expectedVersion); requireActive(p); requireActor(db, ctx); if (p.currentAssigneeId !== ctx.userId) throw new DomainError('FORBIDDEN', 'Somente o responsável atual pode dar ciência.'); const a = getAssignment(db, p); if (!a.receivedAt) { a.receivedAt = new Date().toISOString(); a.receivedById = ctx.userId; bump(p); event(db, { protocolId, kind: 'RECEBIMENTO', actorUserId: ctx.userId, actorUnitId: ctx.activeUnitId, assignmentId: a.id }) }; return p }) },
  async assign(ctx: Context, protocolId: string, expectedVersion: number, assigneeId: string) { return mutate((db) => { const p = getProtocol(db, protocolId); requireVersion(p, expectedVersion); requireActive(p); const actor = requireAdmin(db, ctx); if (ctx.activeUnitId !== p.currentUnitId) throw new DomainError('FORBIDDEN', 'Apenas admin no contexto da unidade atual pode designar responsável.'); const assignee = getUser(db, assigneeId); if (!assignee.active || assignee.unitId !== p.currentUnitId) throw new DomainError('VALIDATION', 'Responsável deve estar ativo e vinculado à unidade atual.'); endCurrent(db, p); const next = addAssignment(db, p, p.currentUnitId, assigneeId); bump(p); event(db, { protocolId, kind: 'ATRIBUICAO', actorUserId: actor.id, actorUnitId: ctx.activeUnitId, toUnitId: p.currentUnitId, toUserId: assigneeId, assignmentId: next.id }); return p }) },
  async forward(ctx: Context, protocolId: string, expectedVersion: number, input: { unitId: string; assigneeId?: string; message: string; dueAt?: string }) { return mutate((db) => { const p = getProtocol(db, protocolId); requireVersion(p, expectedVersion); requireActive(p); requireActor(db, ctx); if (!canAct(db, p, ctx)) throw new DomainError('FORBIDDEN', 'Somente o responsável ou admin no contexto atual pode tramitar.'); requireAssignmentReceived(db, p); const unit = db.units.find((u) => u.id === input.unitId && u.active); if (!unit) throw new DomainError('VALIDATION', 'Selecione uma unidade destino ativa.'); if (!input.message.trim() || input.message.length > 4000) throw new DomainError('VALIDATION', 'Despacho é obrigatório e tem até 4.000 caracteres.'); if (input.dueAt && new Date(input.dueAt) <= new Date()) throw new DomainError('VALIDATION', 'Prazo deve estar no futuro.'); const recipient = input.assigneeId ? getUser(db, input.assigneeId) : undefined; if (recipient && (!recipient.active || recipient.unitId !== input.unitId)) throw new DomainError('VALIDATION', 'O destinatário precisa pertencer à unidade destino.'); if (input.unitId === p.currentUnitId && input.assigneeId === p.currentAssigneeId) throw new DomainError('VALIDATION', 'A tramitação deve alterar unidade ou responsável.'); const oldUnit = p.currentUnitId; const oldUser = p.currentAssigneeId; endCurrent(db, p); const next = addAssignment(db, p, input.unitId, input.assigneeId); p.dueAt = input.dueAt; p.status = 'EM_ANDAMENTO'; bump(p); event(db, { protocolId, kind: 'TRAMITACAO', actorUserId: ctx.userId, actorUnitId: ctx.activeUnitId, fromUnitId: oldUnit, toUnitId: input.unitId, fromUserId: oldUser, toUserId: input.assigneeId, assignmentId: next.id, message: input.message.trim(), previousStatus: 'CADASTRADO', nextStatus: 'EM_ANDAMENTO' }); return p }) },
  async complete(ctx: Context, protocolId: string, expectedVersion: number, message: string) { return mutate((db) => { const p = getProtocol(db, protocolId); requireVersion(p, expectedVersion); requireActive(p); requireActor(db, ctx); if (!canAct(db, p, ctx)) throw new DomainError('FORBIDDEN', 'Você não pode concluir este protocolo.'); requireAssignmentReceived(db, p); if (!message.trim()) throw new DomainError('VALIDATION', 'Informe o resultado da conclusão.'); p.status = 'CONCLUIDO'; p.completedAt = new Date().toISOString(); bump(p); event(db, { protocolId, kind: 'CONCLUSAO', actorUserId: ctx.userId, actorUnitId: ctx.activeUnitId, assignmentId: p.currentAssignmentId, message: message.trim(), previousStatus: 'EM_ANDAMENTO', nextStatus: 'CONCLUIDO' }); return p }) },
  async archive(ctx: Context, protocolId: string, expectedVersion: number) { return mutate((db) => { const p = getProtocol(db, protocolId); requireVersion(p, expectedVersion); requireActor(db, ctx); if (p.status !== 'CONCLUIDO' || !canAct(db, p, ctx)) throw new DomainError('FORBIDDEN', 'Apenas protocolo concluído pode ser arquivado pelo responsável ou admin.'); p.status = 'ARQUIVADO'; p.archivedAt = new Date().toISOString(); bump(p); event(db, { protocolId, kind: 'ARQUIVAMENTO', actorUserId: ctx.userId, actorUnitId: ctx.activeUnitId, assignmentId: p.currentAssignmentId, previousStatus: 'CONCLUIDO', nextStatus: 'ARQUIVADO' }); return p }) },
  async reopen(ctx: Context, protocolId: string, expectedVersion: number, input: { unitId: string; assigneeId?: string; message: string; dueAt?: string }) { return mutate((db) => { const p = getProtocol(db, protocolId); requireVersion(p, expectedVersion); const user = requireAdmin(db, ctx); if (ctx.activeUnitId !== p.currentUnitId || (p.status !== 'CONCLUIDO' && p.status !== 'ARQUIVADO')) throw new DomainError('FORBIDDEN', 'Apenas admin no contexto da unidade atual pode reabrir protocolo concluído ou arquivado.'); if (!input.message.trim()) throw new DomainError('VALIDATION', 'Informe o motivo da reabertura.'); const dest = db.units.find((u) => u.id === input.unitId && u.active); if (!dest) throw new DomainError('VALIDATION', 'Selecione uma unidade destino ativa.'); if (input.assigneeId && getUser(db, input.assigneeId).unitId !== input.unitId) throw new DomainError('VALIDATION', 'Responsável incompatível com a unidade destino.'); endCurrent(db, p); const next = addAssignment(db, p, input.unitId, input.assigneeId); const previous = p.status; p.status = 'EM_ANDAMENTO'; p.completedAt = undefined; p.archivedAt = undefined; p.dueAt = input.dueAt; bump(p); event(db, { protocolId, kind: 'REABERTURA', actorUserId: user.id, actorUnitId: ctx.activeUnitId, toUnitId: input.unitId, toUserId: input.assigneeId, assignmentId: next.id, message: input.message.trim(), previousStatus: previous, nextStatus: 'EM_ANDAMENTO' }); return p }) },
  async addAttachments(ctx: Context, protocolId: string, expectedVersion: number, files: File[]) {
    if (!files.length || files.length > 5) throw new DomainError('VALIDATION', 'Selecione de 1 a 5 arquivos por operação.')
    for (const file of files) if (!['application/pdf', 'image/png', 'image/jpeg', 'text/plain'].includes(file.type) || file.size > 5 * 1024 * 1024) throw new DomainError('VALIDATION', 'Envie PDF, PNG, JPEG ou TXT de até 5 MB.')
    const staged = files.map((file) => ({ file, blobKey: id() }))
    try {
      await cleanupOrphanedBlobs(loadDb().attachments.map((attachment) => attachment.blobKey)).catch(() => undefined)
      await Promise.all(staged.map(({ blobKey, file }) => putBlob(blobKey, file)))
      const attachments = await mutate((db) => {
        const p = getProtocol(db, protocolId); requireVersion(p, expectedVersion); requireActive(p)
        if (!canAct(db, p, ctx)) throw new DomainError('FORBIDDEN', 'Você não pode anexar neste protocolo.')
        const createdAt = new Date().toISOString()
        const created = staged.map(({ file, blobKey }) => {
          const attachment: Attachment = { id: id(), protocolId, filename: file.name, mimeType: file.type, sizeBytes: file.size, blobKey, uploadedById: ctx.userId, createdAt }
          db.attachments.push(attachment)
          event(db, { protocolId, kind: 'ANEXO_ADICIONADO', actorUserId: ctx.userId, actorUnitId: ctx.activeUnitId, assignmentId: p.currentAssignmentId, relatedAttachmentId: attachment.id })
          return attachment
        })
        bump(p)
        return created
      })
      await cleanupOrphanedBlobs(loadDb().attachments.map((attachment) => attachment.blobKey)).catch(() => undefined)
      return attachments
    } catch (error) { await Promise.allSettled(staged.map(({ blobKey }) => deleteBlob(blobKey))); throw error }
  },  async addAttachment(ctx: Context, protocolId: string, expectedVersion: number, file: File) { const [attachment] = await this.addAttachments(ctx, protocolId, expectedVersion, [file]); return attachment },
  async listDocuments(ctx: Context, search = '', typeId = '') { await sleep(); const db = loadDb(); requireActor(db, ctx); const q = search.toLocaleLowerCase(); const items = db.documents.filter((d) => { const p = d.protocolId ? db.protocols.find((x) => x.id === d.protocolId) : undefined; return (!p || canView(db, p, ctx) || d.authorUserId === ctx.userId || d.unitId === ctx.activeUnitId) && (!q || d.number.toLowerCase().includes(q) || d.subject.toLowerCase().includes(q)) && (!typeId || d.typeId === typeId) }); return { items, db } },
  async createDocument(ctx: Context, input: Omit<AppDocument, 'id' | 'number' | 'unitId' | 'authorUserId' | 'createdAt'>) { return mutate((db) => { const author = requireActor(db, ctx); if (!author.active) throw new DomainError('FORBIDDEN', 'Usuário inativo não pode criar documentos.'); if (!input.protocolId && ctx.activeUnitId !== author.unitId) throw new DomainError('FORBIDDEN', 'Documento avulso deve ser criado na unidade de vínculo do usuário.'); const type = db.documentTypes.find((t) => t.id === input.typeId && t.active); if (!type || !input.subject.trim() || !input.body.trim()) throw new DomainError('VALIDATION', 'Preencha tipo, assunto e corpo do documento.'); if (input.recipientPersonId && !db.people.some((person) => person.id === input.recipientPersonId && person.active)) throw new DomainError('VALIDATION', 'Selecione um destinatário ativo.'); if (input.protocolId) { const p = getProtocol(db, input.protocolId); if (!isActive(p) || !canAct(db, p, ctx)) throw new DomainError('FORBIDDEN', 'Documento vinculado exige atuação em protocolo ativo.'); } const doc: AppDocument = { ...input, id: id(), number: nextNumber(db, 'document'), subject: input.subject.trim(), body: input.body.trim(), unitId: ctx.activeUnitId, authorUserId: author.id, createdAt: new Date().toISOString() }; db.documents.push(doc); if (doc.protocolId) event(db, { protocolId: doc.protocolId, kind: 'DOCUMENTO_CRIADO', actorUserId: author.id, actorUnitId: ctx.activeUnitId, relatedDocumentId: doc.id }); return doc }) },
  async listData() { await sleep(); return loadDb() },
  async listPeople(ctx: Context, search = '') { await sleep(); const db = loadDb(); requireActor(db, ctx); const query = search.trim().toLocaleLowerCase(); return { items: db.people.filter((person) => !query || person.name.toLocaleLowerCase().includes(query) || person.document?.includes(query)), db } },
  async createUnit(ctx: Context, input: Omit<Unit, 'id'>) { return mutate((db) => { requireAdmin(db, ctx); const name = input.name.trim(); const abbreviation = input.abbreviation.trim().toUpperCase(); if (!name || !abbreviation) throw new DomainError('VALIDATION', 'Informe nome e sigla da unidade.'); if (db.units.some((unit) => unit.name.toLocaleLowerCase() === name.toLocaleLowerCase() || unit.abbreviation.toLocaleLowerCase() === abbreviation.toLocaleLowerCase())) throw new DomainError('VALIDATION', 'Nome ou sigla já está em uso.'); if (input.parentId && !db.units.some((unit) => unit.id === input.parentId && unit.active)) throw new DomainError('VALIDATION', 'Selecione uma unidade superior ativa.'); const unit: Unit = { id: id(), name, abbreviation, parentId: input.parentId, active: input.active }; db.units.push(unit); return unit }) },
  async updateUnit(ctx: Context, unitId: string, input: Omit<Unit, 'id'>) { return mutate((db) => { requireAdmin(db, ctx); const unit = db.units.find((item) => item.id === unitId); if (!unit) throw new DomainError('NOT_FOUND', 'Unidade não encontrada.'); const name = input.name.trim(); const abbreviation = input.abbreviation.trim().toUpperCase(); if (!name || !abbreviation) throw new DomainError('VALIDATION', 'Informe nome e sigla da unidade.'); if (db.units.some((item) => item.id !== unitId && (item.name.toLocaleLowerCase() === name.toLocaleLowerCase() || item.abbreviation.toLocaleLowerCase() === abbreviation.toLocaleLowerCase()))) throw new DomainError('VALIDATION', 'Nome ou sigla já está em uso.'); if (input.parentId) { const parent = db.units.find((item) => item.id === input.parentId && item.active); if (!parent) throw new DomainError('VALIDATION', 'Selecione uma unidade superior ativa.'); let ancestor: Unit | undefined = parent; while (ancestor) { if (ancestor.id === unitId) throw new DomainError('VALIDATION', 'Uma unidade não pode ser subordinada a si mesma ou a uma descendente.'); ancestor = ancestor.parentId ? db.units.find((item) => item.id === ancestor?.parentId) : undefined } } if (!input.active) { if (db.units.some((item) => item.parentId === unitId && item.active)) throw new DomainError('VALIDATION', 'Não é possível inativar unidade com filhos ativos.'); if (db.users.some((item) => item.unitId === unitId && item.active)) throw new DomainError('VALIDATION', 'Não é possível inativar unidade com usuários ativos vinculados.'); if (db.protocols.some((item) => item.currentUnitId === unitId && isActive(item))) throw new DomainError('VALIDATION', 'Não é possível inativar unidade com protocolos ativos.'); } Object.assign(unit, { name, abbreviation, parentId: input.parentId, active: input.active }); return unit }) },
  async createPerson(ctx: Context, input: PersonInput) { return mutate((db) => { requireActor(db, ctx); validatePerson(input); const person = { ...input, document: input.document?.replace(/\D/g, ''), id: id(), name: input.name.trim() }; db.people.push(person); return person }) },
  async createProtocolType(ctx: Context, input: ProtocolTypeInput) { return mutate((db) => { requireAdmin(db, ctx); validateProtocolType(input); if (db.protocolTypes.some((type) => type.name.toLocaleLowerCase() === input.name.trim().toLocaleLowerCase())) throw new DomainError('VALIDATION', 'Já existe um tipo com este nome.'); const type: ProtocolType = { ...input, id: id(), name: input.name.trim(), description: input.description.trim() }; db.protocolTypes.push(type); return type }) },
  async updateProtocolType(ctx: Context, typeId: string, input: ProtocolTypeInput) { return mutate((db) => { requireAdmin(db, ctx); validateProtocolType(input); const type = db.protocolTypes.find((item) => item.id === typeId); if (!type) throw new DomainError('NOT_FOUND', 'Tipo de protocolo não encontrado.'); if (db.protocolTypes.some((item) => item.id !== typeId && item.name.toLocaleLowerCase() === input.name.trim().toLocaleLowerCase())) throw new DomainError('VALIDATION', 'Já existe um tipo com este nome.'); Object.assign(type, { ...input, name: input.name.trim(), description: input.description.trim() }); return type }) },
  async createDocumentType(ctx: Context, input: Omit<DocumentType, 'id'>) { return mutate((db) => { requireAdmin(db, ctx); const name = input.name.trim(); const description = input.description.trim(); if (!name || !description) throw new DomainError('VALIDATION', 'Informe nome e descrição do tipo.'); if (db.documentTypes.some((type) => type.name.toLocaleLowerCase() === name.toLocaleLowerCase())) throw new DomainError('VALIDATION', 'Já existe um tipo com este nome.'); const type: DocumentType = { ...input, id: id(), name, description }; db.documentTypes.push(type); return type }) },
  async updateDocumentType(ctx: Context, typeId: string, input: Omit<DocumentType, 'id'>) { return mutate((db) => { requireAdmin(db, ctx); const type = db.documentTypes.find((item) => item.id === typeId); if (!type) throw new DomainError('NOT_FOUND', 'Tipo de documento não encontrado.'); const name = input.name.trim(); const description = input.description.trim(); if (!name || !description) throw new DomainError('VALIDATION', 'Informe nome e descrição do tipo.'); if (db.documentTypes.some((item) => item.id !== typeId && item.name.toLocaleLowerCase() === name.toLocaleLowerCase())) throw new DomainError('VALIDATION', 'Já existe um tipo com este nome.'); Object.assign(type, { ...input, name, description }); return type }) },
  async createUser(ctx: Context, input: UserInput) { return mutate((db) => { requireAdmin(db, ctx); validateUser(db, input); const user: AppUser = { ...input, id: id(), name: input.name.trim(), email: input.email.trim().toLocaleLowerCase() }; db.users.push(user); return user }) },
  async updateUser(ctx: Context, userId: string, input: UserInput) { return mutate((db) => { requireAdmin(db, ctx); const user = db.users.find((item) => item.id === userId); if (!user) throw new DomainError('NOT_FOUND', 'Usuário não encontrado.'); validateUser(db, input, userId); if (!input.active && user.active) { if (user.id === ctx.userId) throw new DomainError('VALIDATION', 'Não é possível inativar o usuário atual.'); if (user.role === 'ADMIN' && db.users.filter((item) => item.active && item.role === 'ADMIN').length === 1) throw new DomainError('VALIDATION', 'Não é possível inativar o último administrador ativo.'); if (db.protocols.some((protocol) => isActive(protocol) && protocol.currentAssigneeId === user.id)) throw new DomainError('VALIDATION', 'Redistribua os protocolos ativos antes de inativar este usuário.'); } Object.assign(user, { ...input, name: input.name.trim(), email: input.email.trim().toLocaleLowerCase() }); return user }) },
  async updatePerson(ctx: Context, personId: string, input: PersonInput) { return mutate((db) => { requireAdmin(db, ctx); const person = db.people.find((item) => item.id === personId); if (!person) throw new DomainError('NOT_FOUND', 'Pessoa não encontrada.'); validatePerson(input); Object.assign(person, { ...input, document: input.document?.replace(/\D/g, ''), name: input.name.trim() }); return person }) },
  getBlob
}
export const suggestedDeadline = (days?: number) => days ? isoDaysFromNow(days).slice(0, 16) : ''












