import { expect, test } from '@playwright/test'

test('login apresenta identidade institucional, senha revelável e layout responsivo', async ({ page }, testInfo) => {
  await page.goto('/login')
  await expect(page.getByRole('heading', { name: 'Acesse sua conta' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Preencher acesso de demonstração' })).toBeEnabled()
  await expect(page.getByRole('complementary', { name: 'Navegação principal' })).toHaveCount(0)
  await expect(page.getByRole('textbox', { name: 'E-mail institucional' })).toHaveAttribute('autocomplete', 'username')
  const password = page.getByLabel('Senha', { exact: true })
  await password.fill('Teste de senha')
  await expect(password).toHaveAttribute('type', 'password')
  await page.getByRole('button', { name: 'Mostrar senha' }).click()
  await expect(password).toHaveAttribute('type', 'text')
  await page.getByRole('button', { name: 'Ocultar senha' }).click()
  await expect(password).toHaveAttribute('type', 'password')
  await password.clear()
  await expect(page.getByRole('link', { name: 'Esqueceu sua senha?' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Entrar no sistema' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  expect(await page.evaluate(() => localStorage.getItem('fluxo-publico:user'))).toBeNull()
  await page.evaluate(() => document.fonts.ready)
  await page.mouse.move(0, 0)
  await page.screenshot({ path: testInfo.outputPath('login.png'), fullPage: true })
})

test('valida login, restaura destino, mantém sessão e sai para o login', async ({ page, isMobile }) => {
  await page.goto('/documentos?origem=login')
  await expect(page).toHaveURL(/\/login$/)
  await page.getByLabel('E-mail institucional').fill('marina.duarte@example.com')
  await page.getByLabel('Senha', { exact: true }).fill('senha-incorreta')
  await page.getByRole('button', { name: 'Entrar no sistema' }).click()
  await expect(page.getByRole('alert')).toContainText('E-mail ou senha inválidos')
  await expect(page).toHaveURL(/\/login$/)
  await page.getByRole('button', { name: 'Preencher acesso de demonstração' }).click()
  await page.getByRole('button', { name: 'Entrar no sistema' }).click()
  await expect(page).toHaveURL(/\/documentos\?origem=login$/)
  await expect(page.getByRole('heading', { name: 'Documentos', exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Documentos', exact: true })).toBeVisible()
  expect(await page.evaluate(() => localStorage.getItem('fluxo-publico:user'))).toBe('usr-admin')
  expect(await page.evaluate(() => Object.values(localStorage).some((value) => String(value).includes('Pgci@2026')))).toBe(false)
  if (isMobile) await page.getByRole('button', { name: 'Abrir menu', exact: true }).click()
  await page.getByRole('button', { name: 'Sair', exact: true }).click()
  await expect(page).toHaveURL(/\/login$/)
  await expect(page.getByRole('heading', { name: 'Acesse sua conta' })).toBeVisible()
  expect(await page.evaluate(() => localStorage.getItem('fluxo-publico:user'))).toBeNull()
  await page.goto('/documentos')
  await expect(page).toHaveURL(/\/login$/)
})

test('recuperação valida e-mail e informa honestamente o fluxo demonstrativo', async ({ page }, testInfo) => {
  await page.goto('/login')
  await page.getByRole('link', { name: 'Esqueceu sua senha?' }).click()
  await expect(page).toHaveURL(/\/esqueci-a-senha$/)
  await expect(page.getByRole('heading', { name: 'Esqueceu sua senha?' })).toBeVisible()
  await page.getByLabel('E-mail institucional').fill('email-invalido')
  await page.getByRole('button', { name: 'Recuperar acesso' }).click()
  await expect(page.getByRole('status')).toHaveCount(0)
  await page.getByLabel('E-mail institucional').fill('servidor@prefeitura.gov.br')
  await page.getByRole('button', { name: 'Recuperar acesso' }).click()
  await expect(page.getByRole('status')).toContainText('servidor@prefeitura.gov.br')
  await expect(page.getByRole('status')).toContainText('nenhum e-mail de recuperação é enviado')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('recovery.png'), fullPage: true })
  await page.getByRole('button', { name: 'Informar outro e-mail' }).click()
  await expect(page.getByLabel('E-mail institucional')).toHaveValue('servidor@prefeitura.gov.br')
  await page.getByRole('link', { name: 'Voltar para o login', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Acesse sua conta' })).toBeVisible()
})

test('conta desativada não inicia nem restaura sessão demonstrativa', async ({ page }) => {
  await page.goto('/login')
  await expect(page.getByRole('button', { name: 'Preencher acesso de demonstração' })).toBeEnabled()
  await page.evaluate(() => {
    const key = 'fluxo-publico:database:v1'
    const db = JSON.parse(localStorage.getItem(key)!)
    db.users.find((user: { id: string }) => user.id === 'usr-admin').active = false
    localStorage.setItem(key, JSON.stringify(db))
  })
  await page.getByLabel('E-mail institucional').fill('marina.duarte@example.com')
  await page.getByLabel('Senha', { exact: true }).fill('Pgci@2026')
  await page.getByRole('button', { name: 'Entrar no sistema' }).click()
  await expect(page.getByRole('alert')).toContainText('E-mail ou senha inválidos')
  await page.evaluate(() => localStorage.setItem('fluxo-publico:user', 'usr-admin'))
  await page.goto('/dashboard')
  await expect(page).toHaveURL(/\/login$/)
})
