import { expect, test } from '@playwright/test'
import { PDFDocument } from 'pdf-lib'
import { demoText } from './helpers/demo'
import { expectPdfReady, readPreview } from './helpers/pdf'

test.beforeEach(async ({ page }) => {
  await page.addInitScript(() => {
    if (!localStorage.getItem('fluxo-publico:user')) localStorage.setItem('fluxo-publico:user', 'usr-admin')
    localStorage.setItem('fluxo-publico:unit', 'u-prot')
  })
})

test('anexos têm ícone, menu acessível e edição de nome e descrição persistida', async ({ page }, testInfo) => {
  await page.goto('/processos/pr-1')
  await page.getByRole('button', { name: /^Anexos\b/ }).click()
  let row = page.locator('[data-process-file="attachment"]').filter({ hasText: 'comprovante-demo.txt' })
  await expect(row.locator('svg.lucide-paperclip')).toBeVisible()
  await row.getByText('comprovante-demo.txt', { exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  const actions = row.getByRole('button', { name: 'Ações do anexo comprovante-demo.txt' })
  await actions.press('ArrowDown')
  await expect(page.getByRole('menuitem', { name: 'Ver observação' })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(actions).toBeFocused()
  await actions.click()
  await page.getByRole('menuitem', { name: 'Editar', exact: true }).click()
  const edit = page.getByRole('dialog', { name: 'Editar anexo' })
  await edit.getByLabel('Nome do anexo *').fill('Declaração de recebimento.txt')
  await edit.getByLabel('Descrição').fill('Comprovante conferido pela unidade de protocolo.')
  await edit.getByRole('button', { name: 'Salvar alterações' }).click()
  await expect(edit).toBeHidden()
  await page.reload()
  await page.getByRole('button', { name: /^Anexos\b/ }).click()
  row = page.locator('[data-process-file="attachment"]').filter({ hasText: 'Declaração de recebimento.txt' })
  await expect(row).toContainText('Comprovante conferido pela unidade de protocolo.')
  await row.getByRole('button', { name: /Ações do anexo/ }).click()
  await page.screenshot({ path: testInfo.outputPath('attachment-actions.png') })
  await page.getByRole('menuitem', { name: 'Ver observação' }).click()
  const observation = page.getByRole('dialog', { name: 'Observação', exact: true })
  await expect(observation).toContainText('Comprovante conferido pela unidade de protocolo.')
  await observation.getByRole('button', { name: 'Fechar', exact: true }).click()
  await row.getByRole('button', { name: /Visualizar anexo/ }).click()
  await expect(page.getByRole('dialog', { name: 'Declaração de recebimento.txt' })).toContainText('Comprovante fictício disponível para visualização.')
  const downloading = page.waitForEvent('download')
  await page.getByRole('dialog').getByRole('button', { name: 'Baixar', exact: true }).click()
  expect((await downloading).suggestedFilename()).toBe('Declaração de recebimento.txt')
  await page.getByRole('dialog').getByRole('button', { name: 'Fechar', exact: true }).click()
  await page.getByRole('button', { name: /^Andamento\b/ }).click()
  await expect(page.locator('[data-process-file="attachment"]').filter({ hasText: 'Declaração de recebimento.txt' })).toContainText('Comprovante conferido pela unidade de protocolo.')
})

test('documentos editam metadados e abrem assinatura pelo dropdown sem acessar a página antiga', async ({ page }, testInfo) => {
  await page.goto('/processos/pr-1')
  const number = await demoText(page, 'DOC-2026.000001')
  await page.getByRole('button', { name: /^Documentos\b/ }).click()
  const row = page.locator('[data-process-file="document"]').filter({ hasText: number })
  await expect(row.locator('svg.lucide-file-text')).toBeVisible()
  await row.getByRole('button', { name: `Ações do documento ${number}` }).click()
  await page.getByRole('menuitem', { name: 'Editar', exact: true }).click()
  const edit = page.getByRole('dialog', { name: 'Editar documento', exact: true })
  await expect(edit.getByRole('link', { name: 'Editar conteúdo do documento' })).toHaveAttribute('href', /\/documentos\/doc-1\/editar$/)
  await edit.getByLabel('Nome do documento *').fill('Memorando para conferência')
  await edit.getByLabel('Descrição').fill('Documentação revisada antes do encaminhamento.')
  await edit.getByRole('button', { name: 'Salvar alterações' }).click()
  await expect(edit).toBeHidden()
  await expect(row).toContainText('Memorando para conferência')
  await expect(row).toContainText('Documentação revisada antes do encaminhamento.')
  await row.getByRole('button', { name: `Ações do documento ${number}` }).click()
  await page.getByRole('menuitem', { name: 'Assinar', exact: true }).click()
  const signature = page.getByRole('dialog', { name: 'Assinar eletronicamente', exact: true })
  await expect(page.getByRole('dialog')).toHaveCount(1)
  await expect(page.locator('.pdf-preview-scroll')).toHaveCount(0)
  await expect(signature).toContainText('Memorando para conferência')
  await expect(signature.getByLabel('Assinante')).toHaveValue('Marina Duarte')
  await signature.getByLabel('Cargo / função').fill('Secretária de Administração')
  await signature.getByLabel('Motivo da assinatura').fill('Conferido e aprovado para encaminhamento.')
  await expect(signature.getByRole('button', { name: 'Assinar', exact: true })).toBeEnabled()
  await page.screenshot({ path: testInfo.outputPath('signature-dialog.png') })
  await signature.getByRole('button', { name: 'Assinar', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByRole('status').filter({ hasText: 'Assinatura simulada' })).toContainText('Memorando para conferência')
  await expect(page.locator('.pdf-preview-scroll')).toHaveCount(0)
  await expect(page).toHaveURL(/\/processos\/pr-1$/)
  await page.reload()
  await page.getByRole('button', { name: /^Documentos\b/ }).click()
  await expect(row).toContainText('Memorando para conferência')
})

test('PDF anexado abre assinatura com contexto e mantém o original no download', async ({ page }) => {
  const pdf = await PDFDocument.create()
  pdf.addPage().drawText('Parecer de teste')
  const original = Buffer.from(await pdf.save())
  await page.goto('/processos/pr-1')
  await page.getByRole('button', { name: /^Anexos\b/ }).click()
  await page.locator('input[type="file"]').last().setInputFiles({ name: 'Parecer.pdf', mimeType: 'application/pdf', buffer: original })
  const row = page.locator('[data-process-file="attachment"]').filter({ hasText: 'Parecer.pdf' })
  await row.getByRole('button', { name: 'Ações do anexo Parecer.pdf' }).click()
  await page.getByRole('menuitem', { name: 'Assinar', exact: true }).click()
  const signature = page.getByRole('dialog', { name: 'Assinar eletronicamente' })
  await expect(page.getByRole('dialog')).toHaveCount(1)
  await expect(page.locator('.pdf-preview-scroll')).toHaveCount(0)
  await expect(signature).toContainText('Anexo Parecer.pdf')
  await expect(signature).toContainText('Processo ')
  await signature.getByRole('button', { name: 'Cancelar', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await row.getByRole('button', { name: 'Visualizar anexo Parecer.pdf' }).click()
  const viewer = page.getByRole('dialog', { name: 'Parecer.pdf', exact: true })
  await expectPdfReady(viewer)
  await expect(viewer.getByText('1 assinatura simulada')).toHaveCount(0)
  expect(Buffer.from(await readPreview(page, viewer))).toEqual(original)
})

test('menus ficam junto ao botão em todos os níveis de zoom da interface', async ({ page }, testInfo) => {
  await page.goto('/processos/pr-1')
  const number = await demoText(page, 'DOC-2026.000001')
  for (const zoom of [0.8, 1, 1.2]) {
    await page.evaluate((value) => document.documentElement.style.setProperty('--ui-zoom', String(value)), zoom)
    for (const [tab, label] of [['Documentos', `Ações do documento ${number}`], ['Anexos', 'Ações do anexo comprovante-demo.txt']]) {
      await page.getByRole('button', { name: new RegExp(`^${tab}\\b`) }).click()
      const trigger = page.getByRole('button', { name: label, exact: true })
      await trigger.click()
      const menu = page.getByRole('menu', { name: label, exact: true })
      await expect(menu).toBeVisible()
      const buttonBox = (await trigger.boundingBox())!
      const menuBox = (await menu.boundingBox())!
      expect(Math.abs(menuBox.x + menuBox.width - buttonBox.x - buttonBox.width)).toBeLessThan(2)
      const gap = menuBox.y >= buttonBox.y + buttonBox.height ? menuBox.y - buttonBox.y - buttonBox.height : buttonBox.y - menuBox.y - menuBox.height
      expect(gap).toBeGreaterThanOrEqual(4)
      expect(gap).toBeLessThanOrEqual(8)
      expect(menuBox.x).toBeGreaterThanOrEqual(7)
      expect(menuBox.y).toBeGreaterThanOrEqual(7)
      if (zoom === 0.8 && tab === 'Documentos') await page.screenshot({ path: testInfo.outputPath('actions-zoom-80.png') })
      await page.keyboard.press('Escape')
      await expect(trigger).toBeFocused()
    }
  }
})

test('auditoria traduz vínculo de documento e apresenta ações desconhecidas sem códigos internos', async ({ page }) => {
  await page.goto('/processos/pr-1')
  await expect(page.getByRole('heading', { name: /^Processo / })).toBeVisible()
  await page.evaluate(() => {
    const key = 'fluxo-publico:database:v1'
    const db = JSON.parse(localStorage.getItem(key)!)
    db.auditEvents.push(...['DOCUMENT_LINKED', 'FUTURE_ACTION'].map((action, index) => ({ id: `audit-test-${index}`, action, actorUserId: 'usr-admin', actorUnitId: 'u-prot', targetType: 'DOCUMENT', targetId: 'doc-1', details: `Registro de teste ${index}`, createdAt: new Date().toISOString() })))
    localStorage.setItem(key, JSON.stringify(db))
  })
  await page.reload()
  await page.getByRole('button', { name: /^Auditoria\b/ }).click()
  await expect(page.getByText('Documento vinculado ao processo', { exact: true })).toBeVisible()
  await expect(page.getByText('Ação registrada', { exact: true })).toBeVisible()
  await expect(page.getByText('DOCUMENT_LINKED', { exact: true })).toHaveCount(0)
  await expect(page.getByText('FUTURE_ACTION', { exact: true })).toHaveCount(0)
})

test('consulta sem permissão não oferece edição nem exclusão nos menus', async ({ page }) => {
  await page.goto('/processos/pr-1')
  await expect(page.getByRole('heading', { name: /^Processo / })).toBeVisible()
  await page.evaluate(() => {
    const key = 'fluxo-publico:database:v1'
    const db = JSON.parse(localStorage.getItem(key)!)
    const membership = db.memberships.find((item: { userId: string; unitId: string }) => item.userId === 'usr-clara' && item.unitId === 'u-prot')
    membership.role = 'LEITOR'
    membership.permissions = ['processes.view', 'documents.view']
    localStorage.setItem(key, JSON.stringify(db))
    localStorage.setItem('fluxo-publico:user', 'usr-clara')
  })
  await page.reload()
  await page.getByRole('button', { name: /^Anexos\b/ }).click()
  await page.getByRole('button', { name: 'Ações do anexo comprovante-demo.txt' }).click()
  await expect(page.getByRole('menuitem', { name: 'Editar', exact: true })).toHaveCount(0)
  await expect(page.getByRole('menuitem', { name: 'Excluir', exact: true })).toHaveCount(0)
  await expect(page.getByRole('menuitem', { name: 'Ver observação', exact: true })).toBeVisible()
})
