import { expect, test } from '@playwright/test'

test.beforeEach(async ({ page }) => {
  await page.addInitScript(() => {
    localStorage.setItem('fluxo-publico:user', 'usr-admin')
    localStorage.setItem('fluxo-publico:unit', 'u-prot')
  })
})

test('mantém tipos de processo sem abas redundantes e os cadastros na sidebar', async ({ page }) => {
  await page.goto('/tipos-processo')

  await expect(page.getByRole('heading', { name: 'Tipos de Processo' })).toBeVisible()
  await expect(page.getByRole('tablist', { name: 'Configuração de processos' })).toHaveCount(0)
  await expect(page.locator('a[href="/fases"]')).toHaveCount(1)
  await expect(page.locator('a[href="/categorias-processo"]')).toHaveCount(1)
  await expect(page.locator('a[href="/situacoes"]')).toHaveCount(1)
})

test('exige categoria no cadastro do tipo sem oferecer criação paralela', async ({ page, isMobile }) => {
  await page.goto('/tipos-processo')
  await page.getByRole('button', { name: 'Novo', exact: true }).click()

  const typeDialog = page.getByRole('dialog', { name: 'Novo tipo de processo' })
  const descriptionInput = typeDialog.getByLabel('Descrição *')
  const categorySelect = typeDialog.getByRole('combobox', { name: 'Categoria' })
  await descriptionInput.fill('Tipo com categoria obrigatória')
  const descriptionBox = await descriptionInput.boundingBox()
  const categoryBox = await categorySelect.boundingBox()
  expect(descriptionBox).not.toBeNull()
  expect(categoryBox).not.toBeNull()
  if (!isMobile) expect(Math.abs(descriptionBox!.y - categoryBox!.y)).toBeLessThan(1)
  expect(Math.abs(descriptionBox!.height - categoryBox!.height)).toBeLessThan(1)
  await expect(typeDialog.getByRole('button', { name: 'Nova categoria' })).toHaveCount(0)
  const save = typeDialog.getByRole('button', { name: 'Salvar', exact: true })
  await expect(categorySelect).toContainText('01 — Serviço Público')
  await expect(save).toBeEnabled()
  await categorySelect.click()
  await page.getByRole('option', { name: '02 — Procedimentos Administrativos', exact: true }).click()
  await expect(categorySelect).toContainText('02 — Procedimentos Administrativos')
  await expect(save).toBeEnabled()
})

test('configura campos complementares e autorizações no cadastro do tipo', async ({ page }) => {
  await page.goto('/tipos-processo')
  await page.getByRole('button', { name: 'Novo', exact: true }).click()

  const dialog = page.getByRole('dialog', { name: 'Novo tipo de processo' })
  await expect(dialog.getByRole('switch', { name: 'Tem número de contrato?' })).toBeVisible()
  await expect(dialog.getByRole('switch', { name: 'Tem número de licitação?' })).toBeVisible()
  await expect(dialog.getByRole('switch', { name: 'Tem número de processo jurídico?' })).toBeVisible()
  await expect(dialog.getByRole('switch', { name: 'Tem número?' })).toBeVisible()
  await expect(dialog.getByText('Liberado para todos', { exact: true })).toBeVisible()

  await dialog.getByRole('switch', { name: 'Tem número de contrato?' }).click()
  await dialog.getByRole('checkbox', { name: /Clara Nunes/ }).check()
  await dialog.getByRole('checkbox', { name: /Jurídico/ }).check()
  await expect(dialog.getByText('1 usuário(s) · 1 unidade(s)')).toBeVisible()
})
test('usa fases e situações cadastradas e monta o checklist na etapa', async ({ page }) => {
  await page.goto('/tipos-processo')
  await page.getByRole('button', { name: /Configurar fluxo de Solicitação administrativa/ }).click()
  await page.getByRole('button', { name: 'Nova etapa' }).click()

  const stageDialog = page.getByRole('dialog', { name: 'Nova etapa do fluxo' })
  const checklistLabel = stageDialog.locator('label').filter({ hasText: 'Exige checklist' })
  const attachmentLabel = stageDialog.locator('label').filter({ hasText: 'Exige anexo' })
  await expect(checklistLabel).toHaveClass(/flex/)
  await expect(checklistLabel).toHaveClass(/items-center/)
  await expect(attachmentLabel).toHaveClass(/flex/)
  await expect(attachmentLabel).toHaveClass(/items-center/)
  await expect(stageDialog.getByRole('button', { name: 'Nova fase' })).toHaveText('+ Novo')
  await expect(stageDialog.getByRole('button', { name: 'Nova situação' })).toHaveText('+ Novo')
  await stageDialog.getByRole('combobox', { name: 'Fase *' }).click()
  await page.getByRole('option', { name: 'Formalização da demanda', exact: true }).click()
  await stageDialog.getByRole('combobox', { name: 'Situação' }).click()
  await page.getByRole('option', { name: 'Em tramitação', exact: true }).click()
  await checklistLabel.getByRole('switch').click()
  await expect(stageDialog.getByText('Checklist da etapa')).toBeVisible()
  await expect(stageDialog.getByText('0 pergunta(s)')).toBeVisible()
  await stageDialog.getByRole('button', { name: 'Nova pergunta' }).click()
  const questionDialog = page.getByRole('dialog', { name: 'Nova pergunta' })
  await questionDialog.getByLabel('Pergunta *').fill('Validar dados da solicitação')
  await questionDialog.getByRole('button', { name: 'Salvar', exact: true }).click()

  await expect(questionDialog).toBeHidden()
  await expect(stageDialog.getByText('Validar dados da solicitação')).toBeVisible()
  await expect(stageDialog.getByText('1 pergunta(s)')).toBeVisible()
  await stageDialog.getByRole('button', { name: 'Salvar', exact: true }).click()
  await expect(stageDialog).toBeHidden()
  await expect(page.getByText('1 pergunta(s) no checklist').last()).toBeVisible()
})

test('cria fase e situação sem perder a etapa e seleciona os cadastros novos', async ({ page, isMobile }, testInfo) => {
  await page.setViewportSize({ width: isMobile ? 393 : 1440, height: 560 })
  await page.goto('/tipos-processo')
  await page.getByRole('button', { name: /Configurar fluxo de Solicitação administrativa/ }).click()
  await page.getByRole('button', { name: 'Nova etapa' }).click()
  const stage = page.getByRole('dialog', { name: 'Nova etapa do fluxo' })
  await stage.screenshot({ path: testInfo.outputPath('stage-modal.png') })
  const panel = await stage.locator('.dialog-content').boundingBox()
  expect(panel).not.toBeNull()
  if (!isMobile) expect(panel!.width).toBeGreaterThan(700)
  expect(panel!.width).toBeLessThanOrEqual((page.viewportSize()?.width ?? 0) - 32)
  await stage.getByPlaceholder('Oriente a execução desta etapa...').fill('Preservar a orientação da etapa')

  await stage.getByRole('button', { name: 'Nova fase' }).click()
  let phase = page.getByRole('dialog', { name: 'Novo Tipo de Fase' })
  await phase.getByLabel('Descrição *').fill('Rascunho cancelado')
  await phase.press('Escape')
  await expect(phase).toBeHidden()
  await expect(stage).toBeVisible()
  await expect(stage.getByRole('button', { name: 'Nova fase' })).toBeFocused()
  await expect(stage.getByPlaceholder('Oriente a execução desta etapa...')).toHaveValue('Preservar a orientação da etapa')
  expect(await page.evaluate(() => document.body.style.overflow)).toBe('hidden')

  await stage.getByRole('button', { name: 'Nova fase' }).click()
  phase = page.getByRole('dialog', { name: 'Novo Tipo de Fase' })
  await phase.getByLabel('Descrição *').fill('Conferência criada na etapa')
  await phase.getByRole('button', { name: 'Salvar', exact: true }).click()
  await expect(phase).toBeHidden()
  await expect(stage.getByRole('combobox', { name: 'Fase *' })).toContainText('Conferência criada na etapa')

  await stage.getByRole('button', { name: 'Nova situação' }).click()
  const situation = page.getByRole('dialog', { name: 'Novo Tipo de Situação' })
  await situation.getByLabel('Descrição *').fill('Em conferência da etapa')
  await situation.getByRole('button', { name: 'Salvar', exact: true }).click()
  await expect(situation).toBeHidden()
  await expect(stage.getByRole('combobox', { name: 'Situação', exact: true })).toContainText('Em conferência da etapa')
  await expect(stage.getByPlaceholder('Oriente a execução desta etapa...')).toHaveValue('Preservar a orientação da etapa')
  await stage.getByRole('button', { name: 'Salvar', exact: true }).click()
  await expect(stage).toBeHidden()
  await expect(page.getByRole('heading', { name: 'Conferência criada na etapa', exact: true })).toBeVisible()
  await expect(page.getByText('Em conferência da etapa', { exact: true })).toBeVisible()
})

test('abre o assistente de IA e exige uma descrição suficiente', async ({ page }) => {
  await page.goto('/tipos-processo')
  await page.getByRole('button', { name: 'Criar com IA' }).click()

  const dialog = page.getByRole('dialog', { name: 'Criar tipo de processo com IA' })
  await expect(dialog).toBeVisible()
  await expect(dialog.getByText('Descreva o processo em linguagem natural')).toBeVisible()
  const description = dialog.getByLabel('Como este processo deve funcionar? *')
  const generate = dialog.getByRole('button', { name: 'Gerar proposta' })
  await expect(generate).toBeDisabled()
  await description.fill('Solicitação de compra com análise administrativa, conferência financeira e autorização final.')
  await expect(generate).toBeEnabled()
})
