import { expect, test } from '@playwright/test'

test.beforeEach(async ({ page }) => {
  await page.addInitScript(() => {
    localStorage.setItem('fluxo-publico:user', 'usr-admin')
    localStorage.setItem('fluxo-publico:unit', 'u-prot')
  })
})

test('mantém tipos de processo sem abas redundantes e os cadastros na sidebar', async ({ page }) => {
  await page.goto('/tipos-processo')

  await expect(page.getByRole('heading', { name: 'Tipos de Processo' })).toBeVisible()
  await expect(page.getByRole('tablist', { name: 'Configuração de processos' })).toHaveCount(0)
  await expect(page.locator('a[href="/fases"]')).toHaveCount(1)
  await expect(page.locator('a[href="/categorias-processo"]')).toHaveCount(1)
  await expect(page.locator('a[href="/situacoes"]')).toHaveCount(1)
})

test('exige categoria no cadastro do tipo sem oferecer criação paralela', async ({ page, isMobile }) => {
  await page.goto('/tipos-processo')
  await page.getByRole('button', { name: 'Novo', exact: true }).click()

  const typeDialog = page.getByRole('dialog', { name: 'Novo tipo de processo' })
  const descriptionInput = typeDialog.getByLabel('Descrição *')
  const categorySelect = typeDialog.getByRole('combobox', { name: 'Categoria' })
  await descriptionInput.fill('Tipo com categoria obrigatória')
  const descriptionBox = await descriptionInput.boundingBox()
  const categoryBox = await categorySelect.boundingBox()
  expect(descriptionBox).not.toBeNull()
  expect(categoryBox).not.toBeNull()
  if (!isMobile) expect(Math.abs(descriptionBox!.y - categoryBox!.y)).toBeLessThan(1)
  expect(Math.abs(descriptionBox!.height - categoryBox!.height)).toBeLessThan(1)
  await expect(typeDialog.getByRole('button', { name: 'Nova categoria' })).toHaveCount(0)
  const save = typeDialog.getByRole('button', { name: 'Salvar', exact: true })
  await expect(categorySelect).toContainText('01 — Serviço Público')
  await expect(save).toBeEnabled()
  await categorySelect.click()
  await page.getByRole('option', { name: '02 — Procedimentos Administrativos', exact: true }).click()
  await expect(categorySelect).toContainText('02 — Procedimentos Administrativos')
  await expect(save).toBeEnabled()
})

test('configura campos complementares e autorizações no cadastro do tipo', async ({ page }) => {
  await page.goto('/tipos-processo')
  await page.getByRole('button', { name: 'Novo', exact: true }).click()

  const dialog = page.getByRole('dialog', { name: 'Novo tipo de processo' })
  await expect(dialog.getByRole('switch', { name: 'Tem número de contrato?' })).toBeVisible()
  await expect(dialog.getByRole('switch', { name: 'Tem número de licitação?' })).toBeVisible()
  await expect(dialog.getByRole('switch', { name: 'Tem número de processo jurídico?' })).toBeVisible()
  await expect(dialog.getByRole('switch', { name: 'Tem número?' })).toBeVisible()
  await expect(dialog.getByText('Liberado para todos', { exact: true })).toBeVisible()

  await dialog.getByRole('switch', { name: 'Tem número de contrato?' }).click()
  await dialog.getByRole('checkbox', { name: /Clara Nunes/ }).check()
  await dialog.getByRole('checkbox', { name: /Jurídico/ }).check()
  await expect(dialog.getByText('1 usuário(s) · 1 unidade(s)')).toBeVisible()
})
test('usa fases e situações cadastradas apenas pela sidebar ao montar a etapa', async ({ page }) => {
  await page.goto('/tipos-processo')
  await page.getByRole('button', { name: /Configurar fluxo de Solicitação administrativa/ }).click()
  await page.getByRole('button', { name: 'Nova etapa' }).click()

  const stageDialog = page.getByRole('dialog', { name: 'Nova etapa do fluxo' })
  const checklistLabel = stageDialog.locator('label').filter({ hasText: 'Exige checklist' })
  const attachmentLabel = stageDialog.locator('label').filter({ hasText: 'Exige anexo' })
  await expect(checklistLabel).toHaveClass(/flex/)
  await expect(checklistLabel).toHaveClass(/items-center/)
  await expect(attachmentLabel).toHaveClass(/flex/)
  await expect(attachmentLabel).toHaveClass(/items-center/)
  await expect(stageDialog.getByRole('button', { name: 'Nova fase' })).toHaveCount(0)
  await expect(stageDialog.getByRole('button', { name: 'Nova situação' })).toHaveCount(0)
  await stageDialog.getByRole('combobox', { name: 'Fase *' }).click()
  await page.getByRole('option', { name: 'Formalização da demanda', exact: true }).click()
  await stageDialog.getByRole('combobox', { name: 'Situação' }).click()
  await page.getByRole('option', { name: 'Em tramitação', exact: true }).click()
  await checklistLabel.getByRole('switch').click()
  await expect(stageDialog.getByText('Checklist da etapa')).toBeVisible()
  await expect(stageDialog.getByText('0 pergunta(s)')).toBeVisible()
  await stageDialog.getByRole('button', { name: 'Nova pergunta' }).click()
  const questionDialog = page.getByRole('dialog', { name: 'Nova pergunta' })
  await questionDialog.getByLabel('Pergunta *').fill('Validar dados da solicitação')
  await questionDialog.getByRole('button', { name: 'Salvar', exact: true }).click()

  await expect(questionDialog).toBeHidden()
  await expect(stageDialog.getByText('Validar dados da solicitação')).toBeVisible()
  await expect(stageDialog.getByText('1 pergunta(s)')).toBeVisible()
  await stageDialog.getByRole('button', { name: 'Salvar', exact: true }).click()
  await expect(stageDialog).toBeHidden()
  await expect(page.getByText('1 pergunta(s) no checklist').last()).toBeVisible()
})

test('abre o assistente de IA e exige uma descrição suficiente', async ({ page }) => {
  await page.goto('/tipos-processo')
  await page.getByRole('button', { name: 'Criar com IA' }).click()

  const dialog = page.getByRole('dialog', { name: 'Criar tipo de processo com IA' })
  await expect(dialog).toBeVisible()
  await expect(dialog.getByText('Descreva o processo em linguagem natural')).toBeVisible()
  const description = dialog.getByLabel('Como este processo deve funcionar? *')
  const generate = dialog.getByRole('button', { name: 'Gerar proposta' })
  await expect(generate).toBeDisabled()
  await description.fill('Solicitação de compra com análise administrativa, conferência financeira e autorização final.')
  await expect(generate).toBeEnabled()
})
