import { expect, test } from '@playwright/test'

test.beforeEach(async ({ page }) => {
  await page.addInitScript(() => {
    localStorage.setItem('fluxo-publico:user', 'usr-admin')
    localStorage.setItem('fluxo-publico:unit', 'u-prot')
  })
})

test('usuário não entra nos papéis do processo, mas pessoa sem papel entra em todos', async ({ page }) => {
  await page.goto('/usuarios')
  await page.getByRole('button', { name: 'Novo usuário' }).click()
  const dialog = page.getByRole('dialog', { name: 'Novo usuário' })
  await expect(dialog.getByRole('combobox', { name: 'Pessoa do usuário' })).toHaveCount(0)
  await dialog.getByLabel('Nome do usuário').fill('Carlos Participante')
  await dialog.getByLabel('E-mail do usuário').fill('carlos.participante@example.com')
  await dialog.getByRole('button', { name: 'Salvar' }).click()

  await expect(dialog).toBeHidden()
  const row = page.getByRole('region', { name: 'Lista de usuários' }).locator('article').filter({ hasText: 'Carlos Participante' })
  await expect(row).toContainText('Sem unidade')
  await row.getByRole('link', { name: 'Gerenciar unidades de Carlos Participante' }).click()
  await page.getByRole('button', { name: 'Adicionar unidade' }).click()
  await page.getByRole('dialog', { name: 'Adicionar unidade' }).getByRole('combobox', { name: 'Unidade organizacional' }).click()
  await page.getByRole('option', { name: 'Gestão de Processos', exact: true }).click()
  await page.getByRole('dialog', { name: 'Adicionar unidade' }).getByRole('button', { name: 'Salvar acesso' }).click()
  await expect(page.getByRole('region', { name: 'Unidades e permissões' })).toContainText('Principal')
  await page.goto('/processos/novo')

  await page.getByRole('combobox', { name: 'Tipo de processo *' }).click()
  await page.getByRole('option', { name: 'Pedido de informação' }).click()
  await page.getByRole('combobox', { name: 'Interessado *' }).click()
  await expect(page.getByRole('option', { name: 'Ana Beatriz Costa · Interessado, Responsável' }).locator('.rounded-full')).toHaveCount(2)
  await expect(page.getByRole('option', { name: 'Carlos Participante' })).toHaveCount(0)
  await page.keyboard.press('Escape')
  await page.getByRole('combobox', { name: 'Responsável *' }).click()
  await expect(page.getByRole('option', { name: 'Carlos Participante' })).toHaveCount(0)
  await page.keyboard.press('Escape')

  await page.getByRole('button', { name: 'Cadastrar novo responsável' }).click()
  const personDialog = page.getByRole('dialog', { name: 'Cadastrar pessoa' })
  await personDialog.getByLabel('Nome completo *').fill('Pessoa Universal')
  await personDialog.getByRole('checkbox', { name: 'Responsável' }).uncheck()
  await personDialog.getByRole('button', { name: 'Salvar pessoa' }).click()
  await expect(personDialog).toBeHidden()
  await page.getByRole('combobox', { name: 'Responsável *' }).click()
  await expect(page.getByRole('option', { name: 'Pessoa Universal · Sem papel definido' })).toBeVisible()
  await expect(page.getByRole('option', { name: 'Pessoa Universal · Sem papel definido' }).locator('.rounded-full')).toHaveText('Sem papel definido')
  await page.getByRole('option', { name: 'Pessoa Universal · Sem papel definido' }).click()

  await page.getByRole('combobox', { name: 'Interessado *' }).click()
  await expect(page.getByRole('option', { name: 'Pessoa Universal · Sem papel definido' })).toBeVisible()
  await page.keyboard.press('Escape')

  await page.getByRole('combobox', { name: 'Tipo de processo *' }).click()
  await page.getByRole('option', { name: 'Pagamento de fornecedor' }).click()
  await page.getByRole('combobox', { name: 'Credor *' }).click()
  await expect(page.getByRole('option', { name: 'Carlos Participante' })).toHaveCount(0)
  await expect(page.getByRole('option', { name: 'Pessoa Universal · Sem papel definido' })).toBeVisible()
})

test('importa CSV, cria pessoa opcional e mantém busca e filtros de usuários', async ({ page }) => {
  await page.goto('/usuarios')
  await page.getByRole('button', { name: 'Importar CSV' }).click()
  const dialog = page.getByRole('dialog', { name: 'Importar usuários por CSV' })
  await expect(dialog.getByRole('link', { name: 'Baixar CSV de exemplo' })).toHaveAttribute('href', '/examples/usuarios.csv')
  await dialog.getByLabel('Arquivo CSV').setInputFiles({ name: 'usuarios.csv', mimeType: 'text/csv', buffer: Buffer.from('nome;email;perfil;cpf;ativo;criar_pessoa\nAna Importada;ana.importada@example.com;OPERADOR;;sim;sim\nBeto Importado;beto.importado@example.com;LEITOR;;não;não') })
  await expect(dialog).toContainText('2 usuário(s) encontrado(s) · 0 erro(s)')
  await dialog.getByRole('button', { name: 'Importar usuários' }).click()
  await expect(dialog).toBeHidden()

  await page.getByRole('textbox', { name: 'Buscar usuários' }).fill('ana.importada@example.com')
  const list = page.getByRole('region', { name: 'Lista de usuários' })
  await expect(list.locator('article')).toHaveCount(1)
  await expect(list).toContainText('Ana Importada')
  await expect(list).toContainText('Sem unidade')

  await page.getByRole('textbox', { name: 'Buscar usuários' }).fill('')
  await page.getByRole('button', { name: 'Mais filtros' }).click()
  await page.getByRole('combobox', { name: 'Filtrar usuários por situação' }).click()
  await page.getByRole('option', { name: 'Inativos' }).click()
  await expect(list).toContainText('Beto Importado')
  await expect(list).not.toContainText('Ana Importada')
  await page.getByRole('combobox', { name: 'Filtrar usuários por perfil' }).click()
  await page.getByRole('option', { name: 'Operador' }).click()
  await expect(page.getByText('Nenhum usuário encontrado')).toBeVisible()
  await page.getByRole('combobox', { name: 'Filtrar usuários por perfil' }).click()
  await page.getByRole('option', { name: 'Todos os perfis' }).click()
  await page.goto('/pessoas')
  await page.getByRole('textbox', { name: 'Buscar pessoas' }).fill('Importada')
  await expect(page.getByText('Ana Importada', { exact: true })).toBeVisible()
  await expect(page.getByText('Beto Importado', { exact: true })).toHaveCount(0)
})

test('cadastro individual aceita CPF e cria pessoa pelo switch', async ({ page }) => {
  await page.goto('/usuarios')
  await page.getByRole('button', { name: 'Novo usuário' }).click()
  const dialog = page.getByRole('dialog', { name: 'Novo usuário' })
  await expect(dialog.getByRole('combobox', { name: 'Unidade principal' })).toHaveCount(0)
  await dialog.getByLabel('Nome do usuário').fill('Laura Vínculo')
  await dialog.getByLabel('E-mail do usuário').fill('laura.vinculo@example.com')
  await dialog.getByLabel('CPF do usuário').fill('52998224725')
  await expect(dialog.getByLabel('CPF do usuário')).toHaveValue('529.982.247-25')
  await dialog.getByRole('switch', { name: 'Criar pessoa' }).click()
  await dialog.getByRole('button', { name: 'Salvar' }).click()
  await expect(dialog).toBeHidden()
  await page.getByRole('textbox', { name: 'Buscar usuários' }).fill('52998224725')
  await expect(page.getByRole('region', { name: 'Lista de usuários' })).toContainText('Laura Vínculo')
  await page.getByRole('button', { name: 'Editar usuário Laura Vínculo' }).click()
  await expect(page.getByRole('dialog', { name: 'Editar usuário' }).getByLabel('CPF do usuário')).toHaveValue('529.982.247-25')
  await page.getByRole('dialog', { name: 'Editar usuário' }).getByRole('button', { name: 'Cancelar' }).click()
  await page.goto('/pessoas')
  await page.getByRole('textbox', { name: 'Buscar pessoas' }).fill('52998224725')
  await expect(page.getByRole('region', { name: 'Lista de pessoas' })).toContainText('Laura Vínculo')
})

test('lista usuários e administra unidades e permissões', async ({ page, isMobile }) => {
  await page.goto('/usuarios')

  await expect(page.getByRole('heading', { name: 'Usuários' })).toBeVisible()
  await expect(page.getByRole('region', { name: 'Lista de usuários' }).locator('article')).toHaveCount(6)

  const claraRow = page.getByRole('region', { name: 'Lista de usuários' }).locator('article').filter({ hasText: 'Clara Nunes' })
  await expect(claraRow).toContainText('clara.nunes@example.com')
  await expect(claraRow.getByRole('link', { name: 'Gerenciar unidades de Clara Nunes' })).toContainText('1')
  await claraRow.getByRole('link', { name: 'Gerenciar unidades de Clara Nunes' }).click()

  await expect(page.getByRole('heading', { name: 'Unidades / Permissões — Clara Nunes' })).toBeVisible()
  await expect(page.getByRole('region', { name: 'Unidades e permissões' }).locator('article')).toHaveCount(1)

  await page.getByRole('button', { name: 'Adicionar unidade' }).click()
  const addDialog = page.getByRole('dialog', { name: 'Adicionar unidade' })
  const addDialogBox = await addDialog.locator('section').first().boundingBox()
  expect(addDialogBox).not.toBeNull()
  expect(addDialogBox!.width).toBeLessThanOrEqual(isMobile ? 420 : 576)
  await addDialog.getByRole('combobox', { name: 'Unidade organizacional' }).click()
  await expect(page.getByRole('option', { name: 'Administração / Financeiro', exact: true })).toBeVisible()
  await page.getByRole('option', { name: 'Administração', exact: true }).click()
  await addDialog.getByRole('combobox', { name: 'Permissão nesta unidade' }).click()
  await page.getByRole('option', { name: 'Gestor' }).click()
  await addDialog.getByLabel('Cargo ou função').fill('Coordenadora administrativa')
  await addDialog.getByRole('button', { name: 'Salvar acesso' }).click()

  const accessRegion = page.getByRole('region', { name: 'Unidades e permissões' })
  await expect(accessRegion.locator('article')).toHaveCount(2)
  const administration = accessRegion.locator('article').filter({ hasText: 'Administração' })
  await expect(administration).toContainText('Coordenadora administrativa')
  await expect(administration).toContainText('Gestor')

  await administration.getByRole('button', { name: 'Editar acesso à Administração' }).click()
  const editDialog = page.getByRole('dialog', { name: 'Editar acesso à unidade' })
  await editDialog.getByRole('combobox', { name: 'Permissão nesta unidade' }).click()
  await page.getByRole('option', { name: 'Leitor' }).click()
  await editDialog.getByLabel('Cargo ou função').fill('Consulta administrativa')
  await editDialog.getByRole('button', { name: 'Salvar acesso' }).click()
  await expect(administration).toContainText('Consulta administrativa')
  await expect(administration).toContainText('Leitor')

  await administration.getByRole('button', { name: 'Remover acesso à Administração' }).click()
  const removeDialog = page.getByRole('dialog', { name: 'Remover acesso à unidade?' })
  await removeDialog.getByRole('button', { name: 'Remover acesso' }).click()
  await expect(accessRegion.locator('article')).toHaveCount(1)

  await page.getByRole('link', { name: 'Voltar para usuários' }).click()
  const updatedClara = page.getByRole('region', { name: 'Lista de usuários' }).locator('article').filter({ hasText: 'Clara Nunes' })
  await expect(updatedClara.getByRole('link', { name: 'Gerenciar unidades de Clara Nunes' })).toContainText('1')
})

