import type { ChangeEventHandler } from 'react'
import {
  Archive,
  ArrowLeftRightIcon,
  ArrowRight,
  BadgeInfo,
  Ban,
  Bell,
  BookOpen,
  BriefcaseBusiness,
  Building2,
  CalendarClock,
  Check,
  CheckCircle2,
  CircleCheck,
  CircleDollarSign,
  CircleDollarSignIcon,
  CircleDot,
  CircleHelp,
  CircleX,
  Clipboard,
  ClipboardCheck,
  ClipboardList,
  ClipboardPen,
  Clock3,
  Contact,
  FileArchive,
  FileBadge,
  FileCheck2,
  FilePenLine,
  FilePlus2,
  FileSearch,
  FileText,
  Flag,
  FolderKanban,
  FolderOpen,
  Gavel,
  GitBranch,
  Handshake,
  HeartHandshake,
  KeyRound,
  Landmark,
  ListChecks,
  Mail,
  MapPin,
  Megaphone,
  MessageSquare,
  Network,
  Paperclip,
  RefreshCcw,
  Scale,
  ScanSearch,
  ScrollText,
  Search,
  Send,
  Share2Icon,
  ShieldCheck,
  Signature,
  Stamp,
  Store,
  Tags,
  Trophy,
  UserRound,
  Users,
  WalletCards,
  type LucideIcon,
} from 'lucide-react'
import { Select } from './Select'

export const iconOptions: Array<{ value: string; label: string; Icon: LucideIcon }> = [
  { value: 'FileText', label: 'Documento', Icon: FileText },
  { value: 'Search', label: 'Buscar', Icon: Search },
  { value: 'ArrowLeftRightIcon', label: 'Movimentação', Icon: ArrowLeftRightIcon },
  { value: 'Signature', label: 'Assinatura', Icon: Signature },
  { value: 'Handshake', label: 'Negociação', Icon: Handshake },
  { value: 'CircleDollarSignIcon', label: 'Valores', Icon: CircleDollarSignIcon },
  { value: 'Share2Icon', label: 'Compartilhar', Icon: Share2Icon },
  { value: 'ClipboardList', label: 'Lista', Icon: ClipboardList },
  { value: 'ClipboardPen', label: 'Formulário', Icon: ClipboardPen },
  { value: 'Clipboard', label: 'Prancheta', Icon: Clipboard },
  { value: 'ClipboardCheck', label: 'Prancheta conferida', Icon: ClipboardCheck },
  { value: 'FileCheck2', label: 'Documento conferido', Icon: FileCheck2 },
  { value: 'FileBadge', label: 'Documento certificado', Icon: FileBadge },
  { value: 'FileSearch', label: 'Análise de documento', Icon: FileSearch },
  { value: 'FilePenLine', label: 'Edição de documento', Icon: FilePenLine },
  { value: 'FilePlus2', label: 'Novo documento', Icon: FilePlus2 },
  { value: 'FileArchive', label: 'Documento arquivado', Icon: FileArchive },
  { value: 'FolderOpen', label: 'Pasta aberta', Icon: FolderOpen },
  { value: 'FolderKanban', label: 'Processos organizados', Icon: FolderKanban },
  { value: 'Archive', label: 'Arquivo', Icon: Archive },
  { value: 'Paperclip', label: 'Anexo', Icon: Paperclip },
  { value: 'Flag', label: 'Fase', Icon: Flag },
  { value: 'GitBranch', label: 'Fluxo', Icon: GitBranch },
  { value: 'ListChecks', label: 'Checklist', Icon: ListChecks },
  { value: 'CircleDot', label: 'Situação', Icon: CircleDot },
  { value: 'CircleCheck', label: 'Concluído', Icon: CircleCheck },
  { value: 'CheckCircle2', label: 'Aprovado', Icon: CheckCircle2 },
  { value: 'CircleX', label: 'Cancelado', Icon: CircleX },
  { value: 'Ban', label: 'Rejeitado', Icon: Ban },
  { value: 'RefreshCcw', label: 'Reaberto', Icon: RefreshCcw },
  { value: 'ArrowRight', label: 'Encaminhamento', Icon: ArrowRight },
  { value: 'Check', label: 'Conferência', Icon: Check },
  { value: 'Clock', label: 'Prazo', Icon: Clock3 },
  { value: 'Clock3', label: 'Prazo e horário', Icon: Clock3 },
  { value: 'ShieldCheck', label: 'Controle', Icon: ShieldCheck },
  { value: 'BadgeInfo', label: 'Informação', Icon: BadgeInfo },
  { value: 'Landmark', label: 'Órgão público', Icon: Landmark },
  { value: 'Gavel', label: 'Decisão', Icon: Gavel },
  { value: 'Scale', label: 'Jurídico', Icon: Scale },
  { value: 'ScrollText', label: 'Norma', Icon: ScrollText },
  { value: 'CircleHelp', label: 'Solicitação', Icon: CircleHelp },
  { value: 'BookOpen', label: 'Consulta', Icon: BookOpen },
  { value: 'UserRound', label: 'Pessoa', Icon: UserRound },
  { value: 'Users', label: 'Pessoas', Icon: Users },
  { value: 'Contact', label: 'Cadastro', Icon: Contact },
  { value: 'Handshake', label: 'Acordo', Icon: Handshake },
  { value: 'HeartHandshake', label: 'Atendimento', Icon: HeartHandshake },
  { value: 'BriefcaseBusiness', label: 'Trabalho', Icon: BriefcaseBusiness },
  { value: 'Building2', label: 'Unidade', Icon: Building2 },
  { value: 'Store', label: 'Estabelecimento', Icon: Store },
  { value: 'MapPin', label: 'Localização', Icon: MapPin },
  { value: 'CircleDollarSign', label: 'Financeiro', Icon: CircleDollarSign },
  { value: 'WalletCards', label: 'Pagamento', Icon: WalletCards },
  { value: 'CalendarClock', label: 'Agenda', Icon: CalendarClock },
  { value: 'KeyRound', label: 'Acesso', Icon: KeyRound },
  { value: 'Network', label: 'Estrutura', Icon: Network },
  { value: 'ScanSearch', label: 'Fiscalização', Icon: ScanSearch },
  { value: 'Mail', label: 'Correspondência', Icon: Mail },
  { value: 'MessageSquare', label: 'Comunicação', Icon: MessageSquare },
  { value: 'Megaphone', label: 'Aviso', Icon: Megaphone },
  { value: 'Bell', label: 'Notificação', Icon: Bell },
  { value: 'Send', label: 'Envio', Icon: Send },
  { value: 'Stamp', label: 'Validação', Icon: Stamp },
  { value: 'Tags', label: 'Categoria', Icon: Tags },
  { value: 'Trophy', label: 'Resultado', Icon: Trophy },
]

export function IconGlyph({ name, size = 18, className }: { name?: string; size?: number; className?: string }) {
  const Icon = iconOptions.find((item) => item.value === name)?.Icon ?? FileText
  return <Icon aria-hidden="true" size={size} className={className}/>
}

export function IconSelect({ value, onChange, className = 'field', 'aria-label': ariaLabel = 'Ícone' }: {
  value: string
  onChange: ChangeEventHandler<HTMLSelectElement>
  className?: string
  'aria-label'?: string
}) {
  return <Select aria-label={ariaLabel} className={className} value={value} onChange={onChange}>
    {iconOptions.map(({ value: optionValue, label }) => <option key={optionValue} value={optionValue} aria-label={optionValue}><span className="flex min-w-0 items-center gap-2"><IconGlyph name={optionValue} size={15} className="shrink-0"/><span className="min-w-0 flex-1 truncate">{label}</span><span className="hidden shrink-0 text-[10px] text-muted-foreground sm:inline">{optionValue}</span></span></option>)}
  </Select>
}

